sonar.projectKey=hockey-app
sonar.organization=skippies-io
sonar.cpd.exclusions=scripts/**
sonar.coverage.exclusions=scripts/**,test/**,**/*.test.*,**/*.spec.*,vite.config.js
sonar.exclusions=scripts/**, **/*.test.jsx, **/*.test.js, **/*.spec.js, **/*.spec.ts, e2e/**, .github/**, docs/api.html, db/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
