sonar.projectKey=skippies-io_hockey-app
sonar.organization=lbdc
sonar.cpd.exclusions=scripts/**
sonar.coverage.exclusions=scripts/**,test/**,**/*.test.*,**/*.spec.*,**/*.stories.*,vite.config.js,.storybook/**
sonar.exclusions=scripts/**, **/*.test.jsx, **/*.test.js, **/*.spec.js, **/*.spec.ts, **/*.stories.jsx, e2e/**, .github/**, docs/api.html, db/**, .storybook/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
