export const directoryStyles = {
  container: {
    maxWidth: "1200px",
    margin: "0 auto",
    padding: "var(--hj-space-4)",
  },
  header: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: "var(--hj-space-5)",
    flexWrap: "wrap",
    gap: "var(--hj-space-3)",
  },
  card: {
    backgroundColor: "white",
    borderRadius: "var(--hj-radius-md)",
    padding: "var(--hj-space-5)",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
    marginBottom: "var(--hj-space-4)",
  },
  formRow: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "var(--hj-space-4)",
    alignItems: "end",
  },
  label: {
    display: "block",
    fontWeight: "600",
    fontSize: "0.9rem",
    marginBottom: "var(--hj-space-2)",
    color: "#374151",
  },
  input: {
    width: "100%",
    padding: "8px 12px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontSize: "0.95rem",
    outline: "none",
  },
  textarea: {
    width: "100%",
    padding: "8px 12px",
    border: "1px solid #d1d5db",
    borderRadius: "6px",
    fontSize: "0.95rem",
    outline: "none",
    resize: "vertical",
  },
  actions: {
    display: "flex",
    gap: "var(--hj-space-2)",
    flexWrap: "wrap",
  },
  button: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid transparent",
    backgroundColor: "var(--hj-color-brand-primary)",
    color: "var(--hj-color-inverse-text)",
    cursor: "pointer",
    fontWeight: "600",
  },
  buttonSecondary: {
    padding: "8px 12px",
    borderRadius: "6px",
    border: "1px solid #d1d5db",
    backgroundColor: "white",
    color: "#111827",
    cursor: "pointer",
    fontWeight: "600",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "0.95rem",
    tableLayout: "fixed",
  },
  tableWrapper: {
    overflowX: "auto",
    border: "1px solid #e5e7eb",
    borderRadius: "8px",
  },
  th: {
    textAlign: "left",
    borderBottom: "1px solid #e5e7eb",
    padding: "10px 8px",
    color: "#111827",
  },
  td: {
    padding: "10px 8px",
    borderBottom: "1px solid #f3f4f6",
    verticalAlign: "top",
  },
  cellWrap: {
    whiteSpace: "normal",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  urlText: {
    display: "block",
    color: "#2563eb",
    textDecoration: "none",
    overflowWrap: "anywhere",
    wordBreak: "break-word",
  },
  error: {
    color: "var(--hj-color-danger-ink)",
    marginBottom: "var(--hj-space-3)",
  },
  empty: {
    color: "#6b7280",
  },
  select: {
    padding: "6px 10px",
    borderRadius: "6px",
    border: "1px solid #d1d5db",
    fontSize: "0.85rem",
    backgroundColor: "white",
    color: "#111827",
  },
};
